FROM node:18 AS frontend-build
WORKDIR /vd-frontend
COPY vd-frontend/package*.json ./
RUN npm install
COPY vd-frontend ./
RUN npm run build

FROM node:18
WORKDIR /vd-frontend
COPY --from=frontend-build /vd-frontend ./

EXPOSE 8080
CMD ["npm", "run", "preview"]